FROM node:18-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

COPY . .

ARG STRAPI_API_URL
ARG STRAPI_TOKEN
ENV STRAPI_API_URL=$STRAPI_API_URL
ENV STRAPI_TOKEN=$STRAPI_TOKEN

RUN npm run build

FROM node:18-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/public ./public
EXPOSE 8000
CMD ["serve", "-s", "public", "-l", "8000"]
